"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 3.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR：この設定はプロジェクトの基本となるディレクトリのパスを保持します。
# これは他の設定でファイルやディレクトリのパスを指定する際によく使います。
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY：この秘密鍵は、DjangoがセッションやCSRF保護などのために使用する重要な鍵です。
# これは本番環境では絶対に外部に漏らさないようにしなければなりません。
SECRET_KEY = 'django-insecure-4e3xrzq#htzpk8n668(-3uk1k@cl-afasz6d9tp%5m#!8c=xyr'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG：デバッグモードを有効にする設定です。これがTrueのとき、エラーメッセージが詳細に表示されます。
# ただし、本番環境ではこれをFalseに設定すべきです。
DEBUG = True

# ALLOWED_HOSTS：この設定には、このDjangoアプリケーションをホストすることが許可されているホスト名のリストを指定します。この設定は本番環境で重要になります。
# 現在は全てのホストからのアクセスを許可しています。
ALLOWED_HOSTS = ["*"]

# Application definition
# INSTALLED_APPS：この設定には、プロジェクトで使用するDjangoアプリケーションのリストを指定します。
# ここにアプリケーションの名前を追加すると、Djangoはそのアプリケーションを認識し、対応するデータベーステーブルやテンプレート、管理インターフェースなどを利用できるようになります。
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app_web',
    'todolist',
]

# MIDDLEWARE：ミドルウェアは、Djangoがリクエストとレスポンスを処理する際の処理の流れを制御します。
# ミドルウェアは、セキュリティ対策やセッション管理、メッセージ表示など、多くの重要な機能を提供します。
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ROOT_URLCONF：この設定には、プロジェクトのルートURL設定を指定します。
# Djangoはこの設定を使ってURLとビューをマッピングします。
ROOT_URLCONF = 'myproject.urls'

# TEMPLATES：この設定には、テンプレートエンジンの設定が含まれています。
# テンプレートエンジンは、テンプレートを使ってHTMLを生成するためのツールです。
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

#WSGI_APPLICATION：WSGI（Web Server Gateway Interface）は、Pythonアプリケーションがウェブサーバと通信するための標準化されたインターフェースです。
# この設定には、プロジェクトのWSGIアプリケーションの場所を指定します。
WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
